### ISSUE TITLE
does not work when upgrade mobx and react-mobx-lite

### ISSUE THREAD

**Issue by rxwater** [stolenng/react-hooks-mobx#6]
Dear,
When upgrade form:
```
    "mobx": "^5.15.1",
    "mobx-react-lite": "^1.5.2",
```
to:
`    "mobx": "^6.0.4",
    "mobx-react-lite": "^3.1.6",`

the project can run normally,but Add Tod action does not work, how should i do?

**Comment by rxwater** [comment]
I solved by add makeAutoObservable(this) to constructor

**Comment by stolenng** [comment]
Yea, it's because you installed mobx 6 and it requires makeObservable (this) or makeAutorvable :)
